/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HealthController_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/request-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_requestCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_verify"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ProfilesController_getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ProfilesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profiles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ProfilesController_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profiles/{id}/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["ProfilesController_updateSettings"];
        trace?: never;
    };
    "/api/v1/parent/set-pin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ParentController_setPin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/parent/verify-pin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ParentController_verifyPin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/parent/unlock-next": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ParentController_unlockNext"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/parent/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ParentController_reset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/units": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SessionsController_units"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["SessionsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["SessionsController_complete"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/attempts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AttemptsController_record"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/progress/{profileId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ProgressController_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/digest/{profileId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["DigestController_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/{profileId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ChatController_history"];
        put?: never;
        post: operations["ChatController_send"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/staff/auth/request-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["StaffController_requestCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/staff/auth/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["StaffController_verify"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/staff/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["StaffController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/staff/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["StaffController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/staff/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["StaffController_queue"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/staff/queue/{uploadId}/claim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["StaffController_claim"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/staff/reviews/{uploadId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["StaffController_submit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    HealthController_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_requestCode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        ok: true;
                    };
                };
            };
        };
    };
    AuthController_verify: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    code: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        token: string;
                        isNewAccount: boolean;
                    };
                };
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        ok: true;
                    };
                };
            };
        };
    };
    ProfilesController_getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        account: {
                            id: string;
                            email: string;
                        };
                        profiles: {
                            id: string;
                            name: string;
                            buddy: string;
                            goalPerWeek: number;
                            soundOn: boolean;
                            dyslexicFont: boolean;
                            fontScale: number;
                            stars: number;
                            streakDays: number;
                            unlockedUnit: number;
                            createdAt: string;
                        }[];
                    };
                };
            };
        };
    };
    ProfilesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    /** @enum {string} */
                    buddy?: "nepo" | "stella";
                    goal?: number;
                };
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        profile: {
                            id: string;
                            name: string;
                            buddy: string;
                            goalPerWeek: number;
                            soundOn: boolean;
                            dyslexicFont: boolean;
                            fontScale: number;
                            stars: number;
                            streakDays: number;
                            unlockedUnit: number;
                            createdAt: string;
                        };
                    };
                };
            };
        };
    };
    ProfilesController_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        profile: {
                            id: string;
                            name: string;
                            buddy: string;
                            goalPerWeek: number;
                            soundOn: boolean;
                            dyslexicFont: boolean;
                            fontScale: number;
                            stars: number;
                            streakDays: number;
                            unlockedUnit: number;
                            createdAt: string;
                        };
                        settings: {
                            soundOn: boolean;
                            dyslexicFont: boolean;
                            fontScale: number;
                            goalPerWeek: number;
                            buddy: string;
                        };
                        stars: number;
                        streak: number;
                    };
                };
            };
        };
    };
    ProfilesController_updateSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    soundOn?: boolean;
                    dyslexicFont?: boolean;
                    fontScale?: number;
                    goal?: number;
                    /** @enum {string} */
                    buddy?: "nepo" | "stella";
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        profile: {
                            id: string;
                            name: string;
                            buddy: string;
                            goalPerWeek: number;
                            soundOn: boolean;
                            dyslexicFont: boolean;
                            fontScale: number;
                            stars: number;
                            streakDays: number;
                            unlockedUnit: number;
                            createdAt: string;
                        };
                    };
                };
            };
        };
    };
    ParentController_setPin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    pin: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        ok: true;
                    };
                };
            };
        };
    };
    ParentController_verifyPin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    pin: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        parentToken: string;
                    };
                };
            };
        };
    };
    ParentController_unlockNext: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    profileId: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        ok: true;
                        unlockedUnit: number;
                    };
                };
            };
        };
    };
    ParentController_reset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    profileId: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        ok: true;
                    };
                };
            };
        };
    };
    SessionsController_units: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        unit: number;
                        title: string;
                        subtitle: string;
                        focus: string;
                        exerciseTypes: string[];
                        itemCount: number;
                        /** @enum {string} */
                        status: "locked" | "current" | "done";
                        theme: {
                            iconBg: string;
                            iconColor: string;
                        };
                    }[];
                };
            };
        };
    };
    SessionsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    profileId: string;
                    unit?: number;
                    /** @enum {string} */
                    source?: "bank";
                };
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        sessionId: string;
                        profileId: string;
                        unit: number;
                        generatedAt: string;
                        items: ({
                            /** @enum {string} */
                            type: "count";
                            word: string;
                            syll: string[];
                            answer: number;
                            opts: number[];
                            id: string;
                            audioUrl: string | null;
                            syllableAudio?: string[] | null;
                            skillTags: string[];
                            praise: string;
                        } | {
                            /** @enum {string} */
                            type: "gap";
                            word: string;
                            syll: string[];
                            gapIndex: number;
                            answer: string;
                            options: string[];
                            id: string;
                            audioUrl: string | null;
                            syllableAudio?: string[] | null;
                            skillTags: string[];
                            praise: string;
                        } | {
                            /** @enum {string} */
                            type: "order";
                            word: string;
                            syll: string[];
                            tiles: string[];
                            id: string;
                            audioUrl: string | null;
                            syllableAudio?: string[] | null;
                            skillTags: string[];
                            praise: string;
                        } | {
                            /** @enum {string} */
                            type: "rhyme";
                            word: string;
                            options: string[];
                            answer: string;
                            id: string;
                            audioUrl: string | null;
                            syllableAudio?: string[] | null;
                            skillTags: string[];
                            praise: string;
                        } | {
                            /** @enum {string} */
                            type: "initial";
                            word: string;
                            emoji: string;
                            answer: string;
                            options: string[];
                            id: string;
                            audioUrl: string | null;
                            syllableAudio?: string[] | null;
                            skillTags: string[];
                            praise: string;
                        } | {
                            /** @enum {string} */
                            type: "letter";
                            word: string;
                            letters: string[];
                            gapIndex: number;
                            answer: string;
                            options: string[];
                            id: string;
                            audioUrl: string | null;
                            syllableAudio?: string[] | null;
                            skillTags: string[];
                            praise: string;
                        } | {
                            /** @enum {string} */
                            type: "case";
                            word: string;
                            emoji?: string;
                            answer: string;
                            options: string[];
                            id: string;
                            audioUrl: string | null;
                            syllableAudio?: string[] | null;
                            skillTags: string[];
                            praise: string;
                        } | {
                            /** @enum {string} */
                            type: "arrange";
                            word: string;
                            syll: string[];
                            tiles: string[];
                            id: string;
                            audioUrl: string | null;
                            syllableAudio?: string[] | null;
                            skillTags: string[];
                            praise: string;
                        } | {
                            /** @enum {string} */
                            type: "nonsense";
                            word: string;
                            answer: string;
                            options: string[];
                            id: string;
                            audioUrl: string | null;
                            syllableAudio?: string[] | null;
                            skillTags: string[];
                            praise: string;
                        } | {
                            /** @enum {string} */
                            type: "pairs";
                            tiles: string[];
                            pair: (string)[];
                            id: string;
                            audioUrl: string | null;
                            syllableAudio?: string[] | null;
                            skillTags: string[];
                            praise: string;
                        } | {
                            /** @enum {string} */
                            type: "bd";
                            glyph: string;
                            answer: string;
                            options: string[];
                            id: string;
                            audioUrl: string | null;
                            syllableAudio?: string[] | null;
                            skillTags: string[];
                            praise: string;
                        } | {
                            /** @enum {string} */
                            type: "vowel";
                            word: string;
                            letters: string[];
                            gapIndex: number;
                            answer: string;
                            options: string[];
                            id: string;
                            audioUrl: string | null;
                            syllableAudio?: string[] | null;
                            skillTags: string[];
                            praise: string;
                        } | {
                            /** @enum {string} */
                            type: "swipe";
                            word: string;
                            leftLabel: string;
                            rightLabel: string;
                            /** @enum {string} */
                            answer: "left" | "right";
                            id: string;
                            audioUrl: string | null;
                            syllableAudio?: string[] | null;
                            skillTags: string[];
                            praise: string;
                        } | {
                            /** @enum {string} */
                            type: "odd";
                            words: (string)[];
                            answer: string;
                            instruction: string;
                            id: string;
                            audioUrl: string | null;
                            syllableAudio?: string[] | null;
                            skillTags: string[];
                            praise: string;
                        } | {
                            /** @enum {string} */
                            type: "listen";
                            word: string;
                            instruction: string;
                            options: string[];
                            answer: string;
                            id: string;
                            audioUrl: string | null;
                            syllableAudio?: string[] | null;
                            skillTags: string[];
                            praise: string;
                        } | {
                            /** @enum {string} */
                            type: "sentence";
                            tokens: string[];
                            instruction: string;
                            answer: string;
                            id: string;
                            audioUrl: string | null;
                            syllableAudio?: string[] | null;
                            skillTags: string[];
                            praise: string;
                        } | {
                            /** @enum {string} */
                            type: "build";
                            emoji: string;
                            word: string;
                            tiles: string[];
                            answer: string[];
                            id: string;
                            audioUrl: string | null;
                            syllableAudio?: string[] | null;
                            skillTags: string[];
                            praise: string;
                        })[];
                    };
                };
            };
        };
    };
    SessionsController_complete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        starsAwarded: number;
                        streakDays: number;
                        league: {
                            /** @enum {string} */
                            tier: "bronze" | "silber" | "gold";
                            starsWeek: number;
                            starsToNext: number;
                        };
                    };
                };
            };
        };
    };
    AttemptsController_record: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    sessionId: string;
                    /** Format: uuid */
                    itemId?: string | null;
                    exerciseType: string;
                    prompt: string;
                    expected: string;
                    given: string;
                    isCorrect: boolean;
                    timeMs: number;
                    attemptNo?: number;
                    skillTags: string[];
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        ok: true;
                    };
                };
            };
        };
    };
    ProgressController_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        streakDays: number;
                        stars: number;
                        weeklyActivity: number[];
                        monthlyHeatmap: {
                            date: string;
                            count: number;
                        }[];
                        league: {
                            /** @enum {string} */
                            tier: "bronze" | "silber" | "gold";
                            starsWeek: number;
                            starsToNext: number;
                        };
                        skillBreakdown: {
                            skill: string;
                            attempts: number;
                            correctPct: number;
                            due: boolean;
                        }[];
                    };
                };
            };
        };
    };
    DigestController_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        markdown: string;
                    };
                };
            };
        };
    };
    ChatController_history: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        messages: {
                            me: boolean;
                            text: string;
                            ts: string;
                        }[];
                    };
                };
            };
        };
    };
    ChatController_send: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    text: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        reply: {
                            me: boolean;
                            text: string;
                            ts: string;
                        };
                    };
                };
            };
        };
    };
    StaffController_requestCode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        ok: true;
                    };
                };
            };
        };
    };
    StaffController_verify: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    code: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        reviewerId: string;
                        name: string;
                        /** @enum {string} */
                        role: "reviewer" | "admin";
                    };
                };
            };
        };
    };
    StaffController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        ok: true;
                    };
                };
            };
        };
    };
    StaffController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        reviewerId: string;
                        name: string;
                        /** @enum {string} */
                        role: "reviewer" | "admin";
                    };
                };
            };
        };
    };
    StaffController_queue: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: {
                            uploadId: string;
                            profileHandle: string;
                            gradeBand: string;
                            skillTags: string[];
                            imageUrl: string;
                            llmAnalysis: {
                                topic: string;
                                exerciseType: string;
                                items: {
                                    prompt: string;
                                    childAnswer: string;
                                    correct: boolean;
                                    errorType?: string | null;
                                }[];
                                suggestedFocus: string[];
                            };
                            createdAt: string;
                        }[];
                        nextCursor: string | null;
                    };
                };
            };
        };
    };
    StaffController_claim: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        uploadId: string;
                        claimedUntil: string;
                    };
                };
            };
        };
    };
    StaffController_submit: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    decision: "approved" | "corrected" | "rejected";
                    reviewedAnalysis?: {
                        topic: string;
                        exerciseType: string;
                        items: {
                            prompt: string;
                            childAnswer: string;
                            correct: boolean;
                            errorType?: string | null;
                        }[];
                        suggestedFocus: string[];
                    };
                    notes?: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "reviewed" | "rejected";
                    };
                };
            };
        };
    };
}
