/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HealthController_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/request-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_requestCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_verify"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ProfilesController_getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ProfilesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profiles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ProfilesController_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profiles/{id}/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["ProfilesController_updateSettings"];
        trace?: never;
    };
    "/api/v1/parent/set-pin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ParentController_setPin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/parent/verify-pin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ParentController_verifyPin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/parent/unlock-next": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ParentController_unlockNext"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/parent/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ParentController_reset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/units": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SessionsController_units"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["SessionsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["SessionsController_complete"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/digest/{profileId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["DigestController_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/attempts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AttemptsController_record"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/progress/{profileId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ProgressController_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/{profileId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ChatController_history"];
        put?: never;
        post: operations["ChatController_send"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/homework": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["HomeworkController_upload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/homework/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HomeworkController_result"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/staff/auth/request-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["StaffController_requestCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/staff/auth/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["StaffController_verify"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/staff/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["StaffController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/staff/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["StaffController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/staff/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["StaffController_queue"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/staff/queue/{uploadId}/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["StaffController_queueProgress"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/staff/queue/{uploadId}/claim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["StaffController_claim"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/staff/queue/{uploadId}/release": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["StaffController_release"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/staff/reviews/{uploadId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["StaffController_submit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/staff/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["StaffUsersController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/staff/users/{id}/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["StaffUsersController_accountProgress"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/staff/users/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["StaffUsersController_approve"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/staff/users/{id}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["StaffUsersController_deactivate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/staff/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["StaffUsersController_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    HealthController_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_requestCode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        ok: true;
                    };
                };
            };
        };
    };
    AuthController_verify: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    code: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        token: string;
                        isNewAccount: boolean;
                    };
                };
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        ok: true;
                    };
                };
            };
        };
    };
    ProfilesController_getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        account: {
                            id: string;
                            email: string;
                        };
                        profiles: {
                            id: string;
                            name: string;
                            buddy: string;
                            goalPerWeek: number;
                            soundOn: boolean;
                            dyslexicFont: boolean;
                            fontScale: number;
                            stars: number;
                            streakDays: number;
                            jokerAvailable: boolean;
                            unlockedUnit: number;
                            createdAt: string;
                        }[];
                    };
                };
            };
        };
    };
    ProfilesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    /** @enum {string} */
                    buddy?: "nepo" | "stella" | "charly" | "jax" | "junior" | "li" | "rudolph" | "theo";
                    goal?: number;
                };
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        profile: {
                            id: string;
                            name: string;
                            buddy: string;
                            goalPerWeek: number;
                            soundOn: boolean;
                            dyslexicFont: boolean;
                            fontScale: number;
                            stars: number;
                            streakDays: number;
                            jokerAvailable: boolean;
                            unlockedUnit: number;
                            createdAt: string;
                        };
                    };
                };
            };
        };
    };
    ProfilesController_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        profile: {
                            id: string;
                            name: string;
                            buddy: string;
                            goalPerWeek: number;
                            soundOn: boolean;
                            dyslexicFont: boolean;
                            fontScale: number;
                            stars: number;
                            streakDays: number;
                            jokerAvailable: boolean;
                            unlockedUnit: number;
                            createdAt: string;
                        };
                        settings: {
                            soundOn: boolean;
                            dyslexicFont: boolean;
                            fontScale: number;
                            goalPerWeek: number;
                            buddy: string;
                        };
                        stars: number;
                        streak: number;
                    };
                };
            };
        };
    };
    ProfilesController_updateSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    soundOn?: boolean;
                    dyslexicFont?: boolean;
                    fontScale?: number;
                    goal?: number;
                    /** @enum {string} */
                    buddy?: "nepo" | "stella" | "charly" | "jax" | "junior" | "li" | "rudolph" | "theo";
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        profile: {
                            id: string;
                            name: string;
                            buddy: string;
                            goalPerWeek: number;
                            soundOn: boolean;
                            dyslexicFont: boolean;
                            fontScale: number;
                            stars: number;
                            streakDays: number;
                            jokerAvailable: boolean;
                            unlockedUnit: number;
                            createdAt: string;
                        };
                    };
                };
            };
        };
    };
    ParentController_setPin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    pin: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        ok: true;
                    };
                };
            };
        };
    };
    ParentController_verifyPin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    pin: string;
                    /** Format: uuid */
                    profileId: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        parentToken: string;
                    };
                };
            };
        };
    };
    ParentController_unlockNext: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        ok: true;
                        unlockedUnit: number;
                    };
                };
            };
        };
    };
    ParentController_reset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        ok: true;
                    };
                };
            };
        };
    };
    SessionsController_units: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        unit: number;
                        title: string;
                        subtitle: string;
                        focus: string;
                        exerciseTypes: string[];
                        itemCount: number;
                        /** @enum {string} */
                        status: "locked" | "current" | "done";
                        theme: {
                            iconBg: string;
                            iconColor: string;
                        };
                    }[];
                };
            };
        };
    };
    SessionsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    profileId: string;
                    unit?: number;
                    /** @enum {string} */
                    source?: "bank" | "llm";
                };
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        sessionId: string;
                        profileId: string;
                        unit: number;
                        generatedAt: string;
                        intro?: string;
                        items: {
                            /** @enum {string} */
                            type: "placeholder";
                            prompt: string;
                            options: string[];
                            answer: string;
                            id: string;
                            audioUrl: string | null;
                            syllableAudio?: string[] | null;
                            skillTags: "placeholder"[];
                            praise: string;
                        }[];
                    };
                };
            };
        };
    };
    SessionsController_complete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        starsAwarded: number;
                        streakDays: number;
                        jokerAvailable: boolean;
                        jokerConsumed: boolean;
                        league: {
                            /** @enum {string} */
                            tier: "bronze" | "silber" | "gold";
                            starsWeek: number;
                            starsToNext: number;
                        };
                        allUnitsComplete: boolean;
                    };
                };
            };
        };
    };
    DigestController_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        markdown: string;
                    };
                };
            };
        };
    };
    AttemptsController_record: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    sessionId: string;
                    /** Format: uuid */
                    itemId?: string | null;
                    exerciseType: string;
                    prompt: string;
                    expected: string;
                    given: string;
                    isCorrect: boolean;
                    timeMs: number;
                    attemptNo?: number;
                    skillTags: string[];
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        ok: true;
                    };
                };
            };
        };
    };
    ProgressController_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        streakDays: number;
                        jokerAvailable: boolean;
                        stars: number;
                        weeklyActivity: number[];
                        monthlyHeatmap: {
                            date: string;
                            count: number;
                        }[];
                        league: {
                            /** @enum {string} */
                            tier: "bronze" | "silber" | "gold";
                            starsWeek: number;
                            starsToNext: number;
                        };
                        skillBreakdown: {
                            skill: string;
                            attempts: number;
                            correctPct: number;
                            due: boolean;
                        }[];
                    };
                };
            };
        };
    };
    ChatController_history: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        messages: {
                            me: boolean;
                            text: string;
                            ts: string;
                            imageUrl?: string;
                            /** @enum {string} */
                            homeworkStatus?: "pending_analysis" | "pending_review" | "reviewed" | "rejected";
                        }[];
                    };
                };
            };
        };
    };
    ChatController_send: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    text: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        reply: {
                            me: boolean;
                            text: string;
                            ts: string;
                            imageUrl?: string;
                            /** @enum {string} */
                            homeworkStatus?: "pending_analysis" | "pending_review" | "reviewed" | "rejected";
                        };
                    };
                };
            };
        };
    };
    HomeworkController_upload: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        uploadId: string;
                        /** @enum {string} */
                        status: "pending_analysis" | "pending_review" | "reviewed" | "rejected";
                    };
                };
            };
        };
    };
    HomeworkController_result: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "pending_analysis" | "pending_review" | "reviewed" | "rejected";
                        reviewedAnalysis: {
                            topic: string;
                            exerciseType: string;
                            items: {
                                prompt: string;
                                childAnswer: string;
                                correct: boolean;
                                errorType?: string | null;
                            }[];
                            suggestedFocus: string[];
                        } | null;
                    };
                };
            };
        };
    };
    StaffController_requestCode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        ok: true;
                    };
                };
            };
        };
    };
    StaffController_verify: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    code: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        reviewerId: string;
                        name: string;
                        /** @enum {string} */
                        role: "reviewer" | "admin";
                    };
                };
            };
        };
    };
    StaffController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        ok: true;
                    };
                };
            };
        };
    };
    StaffController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        reviewerId: string;
                        name: string;
                        /** @enum {string} */
                        role: "reviewer" | "admin";
                    };
                };
            };
        };
    };
    StaffController_queue: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: {
                            uploadId: string;
                            profileHandle: string;
                            gradeBand: string;
                            skillTags: string[];
                            imageUrl: string;
                            llmAnalysis: {
                                topic: string;
                                exerciseType: string;
                                items: {
                                    prompt: string;
                                    childAnswer: string;
                                    correct: boolean;
                                    errorType?: string | null;
                                }[];
                                suggestedFocus: string[];
                            };
                            createdAt: string;
                            decision: string | null;
                            reviewedAt: string | null;
                        }[];
                        nextCursor: string | null;
                        total: number;
                    };
                };
            };
        };
    };
    StaffController_queueProgress: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        summary: {
                            unit: number;
                            streakDays: number;
                            stars: number;
                            lastActive: string | null;
                            league: {
                                /** @enum {string} */
                                tier: "bronze" | "silber" | "gold";
                                starsWeek: number;
                                starsToNext: number;
                            };
                        };
                        skills: {
                            skill: string;
                            attempts: number;
                            correctPct: number;
                            due: boolean;
                        }[];
                        activity: {
                            totalAttempts: number;
                            sessions7d: number;
                            sessions30d: number;
                            homework: {
                                uploadId: string;
                                createdAt: string;
                                status: string;
                                decision: string | null;
                                reviewedAt: string | null;
                            }[];
                        };
                        profileHandle: string;
                    };
                };
            };
        };
    };
    StaffController_claim: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        uploadId: string;
                        claimedUntil: string;
                    };
                };
            };
        };
    };
    StaffController_release: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        ok: true;
                    };
                };
            };
        };
    };
    StaffController_submit: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    decision: "approved" | "corrected" | "rejected";
                    reviewedAnalysis?: {
                        topic: string;
                        exerciseType: string;
                        items: {
                            prompt: string;
                            childAnswer: string;
                            correct: boolean;
                            errorType?: string | null;
                        }[];
                        suggestedFocus: string[];
                    };
                    notes?: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "reviewed" | "rejected";
                    };
                };
            };
        };
    };
    StaffUsersController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: {
                            accountId: string;
                            email: string;
                            /** @enum {string} */
                            status: "pending" | "active" | "deactivated";
                            createdAt: string;
                            profileCount: number;
                            lastActive: string | null;
                        }[];
                        nextCursor: string | null;
                        total: number;
                    };
                };
            };
        };
    };
    StaffUsersController_accountProgress: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        profiles: {
                            summary: {
                                unit: number;
                                streakDays: number;
                                stars: number;
                                lastActive: string | null;
                                league: {
                                    /** @enum {string} */
                                    tier: "bronze" | "silber" | "gold";
                                    starsWeek: number;
                                    starsToNext: number;
                                };
                            };
                            skills: {
                                skill: string;
                                attempts: number;
                                correctPct: number;
                                due: boolean;
                            }[];
                            activity: {
                                totalAttempts: number;
                                sessions7d: number;
                                sessions30d: number;
                                homework: {
                                    uploadId: string;
                                    createdAt: string;
                                    status: string;
                                    decision: string | null;
                                    reviewedAt: string | null;
                                }[];
                            };
                            profileId: string;
                            name: string;
                        }[];
                    };
                };
            };
        };
    };
    StaffUsersController_approve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        accountId: string;
                        /** @enum {string} */
                        status: "pending" | "active" | "deactivated";
                    };
                };
            };
        };
    };
    StaffUsersController_deactivate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        accountId: string;
                        /** @enum {string} */
                        status: "pending" | "active" | "deactivated";
                    };
                };
            };
        };
    };
    StaffUsersController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
