/**
 * Shared base⊕override diff logic — used by the export CLI (scripts/export-overrides.ts) and the
 * reviewer "export corrections" endpoint. Produces the minimal change-set (field-level edits, added
 * words, deleted lemmas) between the live `lexeme` table and the PDF-extracted base (lexeme.seed.json).
 * Self-healing: if the base later catches up to a correction, that override drops out of the diff.
 */

export const LEXEME_OVERRIDE_FIELDS = [
  'hk', 'pos', 'genus', 'morphemeCount', 'ipa', 'syllabification', 'syllableCount',
  'forms', 'separablePrefix', 'familyStem', 'compoundParts', 'features', 'skillTags',
  'isLernwort', 'isTrennbar', 'isMerkwort',
] as const;

export type LexemeField = (typeof LEXEME_OVERRIDE_FIELDS)[number];

export interface LexemeRecord {
  lemma: string;
  hk: number;
  pos: string;
  genus: string | null;
  morphemeCount: number;
  ipa: string;
  syllabification: string;
  syllableCount: number;
  forms: string | null;
  separablePrefix: string | null;
  familyStem: string | null;
  compoundParts: string[];
  features: unknown;
  skillTags: string[];
  isLernwort: boolean;
  isTrennbar: boolean;
  isMerkwort: boolean;
  source?: string;
}

export interface LexemeOverrides {
  edits: Record<string, Record<string, unknown>>;
  adds: Record<string, unknown>[];
  deletes: string[];
}

export const OVERRIDES_COMMENT =
  'Human corrections layered on top of lexeme.seed.json (the PDF-extracted base). Regenerated by `npm run export:overrides` (or the reviewer portal) from the DB-vs-base diff; edit via the reviewer portal, not by hand. Applied after the base on every seed, so corrections survive reseeds and reproduce in any fresh DB. edits = sparse per-lemma field patches (field-level); adds = new records; deletes = removed base lemmas.';

/** Order-independent canonical string: sorts object keys (jsonb key order isn't stable) and skill-tag sets. */
function canon(field: string, v: unknown): string {
  if (field === 'skillTags' && Array.isArray(v)) return JSON.stringify([...v].sort());
  const walk = (x: unknown): unknown => {
    if (Array.isArray(x)) return x.map(walk);
    if (x && typeof x === 'object') {
      return Object.fromEntries(
        Object.keys(x as object)
          .sort()
          .map((k) => [k, walk((x as Record<string, unknown>)[k])]),
      );
    }
    return x ?? null;
  };
  return JSON.stringify(walk(v));
}

function pick(row: LexemeRecord): Record<string, unknown> {
  const r: Record<string, unknown> = { lemma: row.lemma };
  for (const f of LEXEME_OVERRIDE_FIELDS) r[f] = (row as unknown as Record<string, unknown>)[f] ?? null;
  r.source = row.source ?? 'reviewer';
  return r;
}

/** Diff the live rows against the base → the minimal, sorted, deterministic change-set. */
export function computeOverrides(base: LexemeRecord[], dbRows: LexemeRecord[]): LexemeOverrides {
  const baseByLemma = new Map(base.map((r) => [r.lemma, r]));
  const dbLemmas = new Set(dbRows.map((r) => r.lemma));

  const edits: Record<string, Record<string, unknown>> = {};
  const adds: Record<string, unknown>[] = [];
  const deletes: string[] = [];

  for (const row of dbRows) {
    const b = baseByLemma.get(row.lemma);
    if (!b) {
      adds.push(pick(row)); // in DB, not in base → an added word
      continue;
    }
    const patch: Record<string, unknown> = {};
    for (const f of LEXEME_OVERRIDE_FIELDS) {
      const cur = (row as unknown as Record<string, unknown>)[f] ?? null;
      const bas = (b as unknown as Record<string, unknown>)[f] ?? null;
      if (canon(f, cur) !== canon(f, bas)) patch[f] = cur;
    }
    if (Object.keys(patch).length) edits[row.lemma] = patch;
  }
  for (const b of base) if (!dbLemmas.has(b.lemma)) deletes.push(b.lemma);

  return {
    edits: Object.fromEntries(Object.keys(edits).sort().map((k) => [k, edits[k]])),
    adds: adds.sort((a, b) => String(a.lemma).localeCompare(String(b.lemma))),
    deletes: deletes.sort(),
  };
}

/** The on-disk shape (change-set + the human-facing comment header). */
export function overridesFile(o: LexemeOverrides): Record<string, unknown> {
  return { _comment: OVERRIDES_COMMENT, edits: o.edits, adds: o.adds, deletes: o.deletes };
}
